version: '3.8'

services:
  app:
    container_name: teste-boticario
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=devsecret